# Generated by Django 4.2 on 2023-10-18 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SendEmailApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtemplate',
            name='event_name',
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SendEmailApp.employee'),
            preserve_default=False,
        ),
    ]
