# Generated by Django 4.2 on 2023-10-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendEmailApp', '0002_remove_eventtemplate_event_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtemplate',
            name='employee',
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='event_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
