# Generated by Django 4.2 on 2023-10-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SendEmailApp', '0003_remove_eventtemplate_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtemplate',
            old_name='event_name',
            new_name='event_namefor',
        ),
    ]
